version: '3'
services:
  postgres:
    image: "postgres:${VERSION}"
    container_name: java-postgres
    ports:
      - "${POSTGRES_PORTS}"
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: "historicalplaceimage:${VERSION}"
    container_name: HistoricalPlaces
    ports:
      - "${APP_PORTS}"
    environment:
      POSTGRES_HOST: postgres
    restart: always
    links:
      - postgres
      - rabbitmq
      - app2
    depends_on:
      - postgres
      - rabbitmq
      - app2
  app2:
    image: "microservice:${VERSION}"
    container_name: microservice
    ports:
      - "${APP2_PORTS}"
    environment:
      POSTGRES_HOST: postgres
    restart: always
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:${RABBIT_VERSION}"
    container_name: rabbitmq
    ports:
      - "${RABBIT_PORTS_INNER}"
      - "${RABBIT_PORTS_OUT}"