spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/HistoricalPlacesData
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

jwt:
  header: "Authorization"
  secret: "youaretooyoungtobeafraidoffailure"
  expiration: "604800"

rabbit:
  exchange: myrabbitmq.direct
  routing-key: myrabbitmq.routingkey
  default-receive-queue: myrabbitmq.queue

#server:
#  port: 8081
